# prettier-ignore

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: COSMOS_ENDPOINT
              value: "{{ .Values.env.COSMOS_ENDPOINT }}"
            - name: COSMOS_KEY
              valueFrom:
                secretKeyRef:
                  name: cosmos-secret
                  key: key
            - name: COSMOS_DATABASE
              value: "{{ .Values.env.COSMOS_DATABASE }}"
            - name: COSMOS_CONTAINER
              value: "{{ .Values.env.COSMOS_CONTAINER }}"
            - name: COSMOS_PARTITION_KEY
              value: "{{ .Values.env.COSMOS_PARTITION_KEY }}"
